services:
  api:
    ports:
      - 8080:8080
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
